name: checkov-static-analysis-scan
on:
  push:
    branches: ['*']
    paths-ignore:
      - '**/README.md'
    

  pull_request:
    branches: ['main', 'dev', 'stage']
    paths-ignore:
       - '**/README.md'
  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch:
permissions: read-all
jobs:
  scan:
    permissions:      
      contents: read # for actions/checkout to fetch code
      actions: read  # only required for a private respository by gihub/codeql-action/upload-sarif to get the action run status
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    runs-on: ubuntu-latest # The type of runner that the job will run on.

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v3.5.0

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infrastructure/
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif